<%@taglib uri="http://java.sun.com/jsp/jstl/fmt"   		prefix="fmt"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions"  prefix="fn"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core"  		prefix="c"%>	
<%@taglib uri="http://struts.apache.org/tags-bean" 		prefix="bean"%> 
<%@taglib uri="http://displaytag.sf.net" 		   		prefix="display"%>
<%@taglib uri="http://ajaxtags.org/tags/ajax" 	   		prefix="ajax"%>
<%@taglib uri="/WEB-INF/tld/struts-html.tld" 		   	prefix="html"%>
<%@taglib uri="/WEB-INF/tld/struts-logic.tld"		  	prefix="logic"%> 
<%@taglib uri="/WEB-INF/tld/utils.tld"  				prefix="util"%>